### PR TITLE
Fixes for StoreAdapt=TRUE in regression case, and for plot function for NoSpikes chains

### PR DESCRIPTION
**Pull request by Alanocallaghan**
- Prevent BASiCS_Chain from crashing when StoreAdapt=TRUE (regression case, spikes and no spikes)
  
  sigma was transposed, when it shouldn't be, in this instance. Also, makes
  some failure conditions more explicit.

  Removes DesignMatrix from test of dimensionality.
- Prevent plot function errors
  
  Move some dependencies in Imports
  build NAMESPACE using Roxygen

  Set plot function generic before attaching method
  Other minor changes to documentation

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
@catavallejos - stumbled across this bug while refactoring some of the C++ files. The test I added should fail if you remove the changes to `R/Classes.R` or to `src/BASiCS_MCMCcppRegNoSpikes.cpp`. I have some more changes (just refactoring so far) coming, so I'm happy to add these to this PR, unless you want to merge it sooner

**Comment by nilseling** [comment]
Hi Alan,
thanks a lot for doing these changes! I noticed that BASiCS broke due to a recent update in scran. Would it be possible if you merge the changes in the "Devel" branch into your PR? Or maybe issue a PR into "Devel"? That allows me to merge both of our changes into the master branch at some point.
Cheers,
Nils

**Comment by Alanocallaghan** [comment]
Cheers Nils, thanks for merging. Do you tend to work with git flow on this repo then? (sacred master, develop branch for work between releases, feature branches merged into develop)

**Comment by nilseling** [comment]
I actually wasn't aware of git flow. But we usually kept the system of master and develop branches. It makes it easier to test the model and correct for errors while keeping the master branch intact. I just opened the Devel branch to prepare some changes for the next Bioconductor release. Feel free to send PR whenever you have things that you want to merge first into Devel and then into master.

**Comment by Alanocallaghan** [comment]
Yep makes sense. The alternative is github flow (no develop branch, bugfixes/features go right into master) but you can end up with a broken master much easier that way.

Cheers will do, likely nothing major for the next while. Grats for the paper and for submitting your thesis btw!

**Comment by nilseling** [comment]
Thanks :) I'm also looking forward to your changes to BASiCS!
Let's keep the master/develop branch for now since it worked out quite nicely in the last Bioconductor update.

**Comment by catavallejos** [comment]
Thank you Alan and Nils for making these changes! I will push to Bioconductor now.
Best,
Cata

**Pull request merged**
