### PR TITLE
Add diagPlot and diagHist functions

### LINKED ISSUE #69: Add effectiveSize plot function
Plot parameters values as x and y, with colour being coda::effectiveSize for one of the parameters

### PR DESCRIPTION
**Pull request by Alanocallaghan**
Add functions for visualising diagnostic measures from coda
(currently only effectiveSize and geweke.diag)
across multiple parameters simultaneuously.
geweke.diag is probably an odd inclusion and might be removed.
Also some incidental refactoring.

Resolve #69

Diagnostic plot (in this case mu vs delta with mu ESS)
p

ESS across all parameters
h_all

ESS for mu only
h_mu

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
Added the ESS(Param) vs Param plot (see below). Also remove `geweke.diag` for the time being as I don't know how well used or applicable it is, though adding other diagnostics in future is a reasonable idea.

d

**Comment by catavallejos** [comment]
Thanks Alan! I agree about removing `geweke.diag` for now. We can add later if needed.

**Comment by catavallejos** [comment]
Hi Alan,

I merged this into the devel branch. Just a couple of comments/requests:

- I can see that you created generic methods for `diagPlot` and `diagHist`. Perhaps it's better to change this to `BASiCS_diagPlot` and `BASiCS_diagHist`? In particular, `diagPlot` seems to be a somewhat popular name and there is a risk of conflict with other libraries. 
- Some of the new functions should be private (I think). Among others, these include `getMeasure`, `geneParams`, etc. Renaming these as e.g. `HiddengeneParams` should do the job.

Best

Cata

**Comment by Alanocallaghan** [comment]
>I can see that you created generic methods for diagPlot and diagHist. Perhaps it's better to change this to BASiCS_diagPlot and BASiCS_diagHist? In particular, diagPlot seems to be a somewhat popular name and there is a risk of conflict with other libraries.

I don't think that the `BASiCS_*` prefix is the best way to avoid namespace conflicts, since if a conflict exists, users will essentially do that anyway (`BASiCS::*`) and if not, you force users to prepend the function name. Having said that, better to have consistent function names so better to stick with it at this point. I would say that it would probably better to have this consistent across all functions (exceptions include `newBASiCS_Data` and `displayChainBASiCS`, which under this scheme should be `BASiCS_newData` and `BASiCS_displayChain` respectively.

> On a related note, the call to setGeneric("plot") can be problematic as it is likely to conflict with other libraries. As far as I understand, this is not needed.

Even importing plot from graphics, the code below will error (in this commit I removed the call to setGeneric).
```r
library("devtools")
library("BASiCS")    

install_github("Alanocallaghan/BASiCS", ref="c7b8bb040fcad793148efa848fbc0e0ffb31a4c1")

Data <- makeExampleBASiCS_Data()
Chain <- BASiCS_MCMC(Data, N = 10000, Thin = 2, Burn = 10, Regression = FALSE, PrintProgress = FALSE, WithSpikes = TRUE)
plot(Summary)
# Error in (function (classes, fdef, mtable)  : 
#  unable to find an inherited method for function ‘Summary’ for signature ‘"numeric"’
```

> Some of the new functions should be private (I think). Renaming these as e.g. HiddengeneParams should do the job.

Sorry, I'm used to defining the interface of the package by marking functions for export with a roxygen tag, rather than using exportPattern. I am likely to forget about this occasionally so apologies.

**Comment by catavallejos** [comment]
Thanks @Alanocallaghan !

**Comment by Alanocallaghan** [comment]
Whoops, there's a typo in the example I gave above for which easily explains the bug. Not sure why I was running into this issue before (may have been reloading the package locally), if I encounter again I'll try to make a proper fix

**Pull request merged**
