### PR TITLE
CheckESS argument

### PR DESCRIPTION
**Pull request by Alanocallaghan**
This should only contain cdc9332

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
Add our own ess function

```r
library("BASiCS")
library("coda")
library("microbenchmark")

ess <- function(mat) {
  spec <- apply(mat, 2, 
    function(x) {
      a <- ar(x, aic = TRUE)
      a$var.pred / (1 - sum(a$ar)) ^ 2
    }
  )
  ifelse(spec == 0, 0, nrow(mat) * colVars(mat) / spec)
}

all.equal(ess(ChainSC@parameters[["mu"]]), effectiveSize(ChainSC@parameters[["mu"]]))
microbenchmark(ess(ChainSC@parameters[["mu"]]), effectiveSize(ChainSC@parameters[["mu"]]))
```

**Comment by Alanocallaghan** [comment]
Apparently somebody's removed a space in the travis build scripts :) :) :) :)

**Comment by Alanocallaghan** [comment]
I can squash this and write a proper commit message (rather than my chickenscratch) if you prefer

**Comment by catavallejos** [comment]
Thanks Alan. Looks good. However, I have two comments:]

1. Perhaps we should add a note to mention that the internal ess function is inspired by the one in the coda package? (btw - we do need to check the licence they have)
2. I couldn't find the `MinESS` parameter that you are mentioning in the NEWS file. Also, what will be the default value for that?

**Comment by Alanocallaghan** [comment]
1 - GPL 2, same as us, but yeah I'll add a note.
2 - CheckESS

**Comment by catavallejos** [comment]
Ops, just saw it. There is a `ESSThreshold` parameter. Maybe you can switch to `MinESS`?

**Comment by catavallejos** [comment]
Sorry, one extra comment. I think we should exclude the genes with low ESS from the EFDR calibration that calls `.ThresholdSearch`. We are effectively excluding those genes from testing, similar to what we do with `GenesSelect`.

**Comment by catavallejos** [comment]
I think you do that for delta and epsilon, but just saw it's missing for mu.

**Comment by Alanocallaghan** [comment]
Should all be fixed in 28a1a987de

**Comment by catavallejos** [comment]
Thanks! I will merge once the checks are ready (please do remind me if I don't!)

**Comment by Alanocallaghan** [comment]
Will do, I want to finish the rewrites of the TestDE code soon

**Comment by Alanocallaghan** [comment]
So tests are currently run with `CheckESS=FALSE`, so I'll add tests with `CheckESS=TRUE` (the new default).

**Pull request merged**
