### PR TITLE
Ensure consistency in plot names. Add utility functions.

### LINKED ISSUE #108: TestDE (silently) requires equal number of samples
This isn't a problem but currently it fails with a non-informative error message:
```
Error in Chain1@parameters$mu/Chain2@parameters$mu : 
  non-conformable arrays
In addition: Warning message:
In matrixStats::rowSums2(Chain1@parameters$mu)/matrixStats::rowSums2(Chain2@parameters$mu) :
  longer object length is not a multiple of shorter object length
```

### PR DESCRIPTION
**Pull request by Alanocallaghan**
Add Smooth option (useful for when hexbin is not resolved).

Resolve #108

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
Can merge these to newdevel/Devel if it's easier

**Comment by catavallejos** [comment]
Merged into master, but NEWS not updated.

@Alanocallaghan could you please update NEWS? I will then push to BioC devel

**Comment by Alanocallaghan** [comment]
Yeah will do tomorrow morning

**Comment by catavallejos** [comment]
Thanks! no rush!

**Pull request merged**
