### PR TITLE
v2.2.3, no error for single batch

### PR DESCRIPTION
**Pull request by Alanocallaghan**
This somehow got lost (undoubtedly my oversight)  #186

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
@catavallejos - the two PRs should be good to go if you want to review and squash. Just took some time to get the tests right so that I don't make the same mistake again.

**Comment by catavallejos** [comment]
thanks! on my to-do list

**Comment by Alanocallaghan** [comment]
@catavallejos - should be all good. Largely bugfixes. #226 is the same content but for master and includes the maintainer change. I don't think changing it on release is necessary

**Review by catavallejos — APPROVED** [review]

**Comment by catavallejos** [comment]
Thanks @Alanocallaghan can you re-submit the PR to merge in `master`? This was merged into `RELEASE_3_12`, but it's `master` what is in sync with Biocdevel.

**Comment by Alanocallaghan** [comment]
Yeah that was intended. Unlikely anybody spots these as they're all related to divide and conquer but I think it's good to fix known bugs before this release version is frozen

**Comment by catavallejos** [comment]
Agreed. Can you fix the dates for the RELEASE_3_12 branch too?

**Comment by Alanocallaghan** [comment]
Done deal

**Pull request merged**
