### PR TITLE
Summary arg order

### PR DESCRIPTION
**Pull request by alanocallaghan**
Just trying to fix my bioc packages and spotted this along the way. I can't get R 4.4 installed to properly run checks, but it solves one of the issues at least

### CODE REVIEW

**Comment by alanocallaghan** [comment]
Actually, I just tested it on R-devel and the tests pass, at least. Check fails for me with some bizarre font issue, but I think it's unrelated

**Comment by lazappi** [comment]
@catavallejos Would it be possible to merge this and push it to Bioconductor? At the moment, any package that depends on **{BASiCS}** is failing on the devel branch because of this. Thanks!

**Comment by catavallejos** [comment]
So sorry for the delay @lazappi and @alanocallaghan . Merged and will push to Bioc now.

Best

Cata

**Comment by catavallejos** [comment]
Hi @lazappi - after pushing I saw there was a small typo in one of the examples that led to errors in BioC. That should be fixed now.

**Pull request merged**
