### PR TITLE
Namespace, doc & test changes

### PR DESCRIPTION
**Pull request by Alanocallaghan**
- Switch some generics to be functions
- Prefix more methods with `pkg::fun`
- Move packages to imports
- Fix documentation warnings
- capture.output for BASiCS_MCMC in tests

### CODE REVIEW

**Comment by catavallejos** [comment]
@Alanocallaghan just merged this to the devel. 

Just one minor comment. I think it's best to have individual files for all the functions that are exported. That can be helpful whenever we need to edit each function.

**Comment by Alanocallaghan** [comment]
Sure - btw it's probably easier to comment before merging so all the related changes are in one place

**Comment by catavallejos** [comment]
I will do that now when I update the version number and NEWS.

**Comment by catavallejos** [comment]
Sure! I will do that next time!

**Pull request merged**
